# Changes here will be overwritten by Copier; NEVER EDIT MANUALLY
_commit: 1.8.0
_src_path: gh:algorandfoundation/algokit-python-template
author_email: 144294907+rendidwi2604@users.noreply.github.com
author_name: rendidwi2604
contract_name: crowfunding
deployment_language: python
preset_name: starter
project_name: crowfuding

